//FOODS ACTIONS
export const LOAD_FOODS = 'LOAD_FOODS'

export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS'
export const SORT_FOODS = 'SORT_FOODS'
export const SEARCH_FOODS = 'SEARCH_FOODS'
export const GET_FOODS_BEGIN = 'GET_FOODS_BEGIN'
export const GET_FOODS_ERROR = 'GET_FOODS_ERROR'
export const GET_SINGLE_FOOD_SUCCESS = 'GET_SINGLE_FOOD_SUCCESS'
export const GET_SINGLE_FOOD_BEGIN = 'GET_SINGLE_FOOD_BEGIN'
export const GET_SINGLE_FOOD_ERROR = 'GET_SINGLE_FOOD_ERROR'
//CART ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const CLEAR_CART = 'CLEAR_CART'
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS'
//USER ACTIONS
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOG_OUT_USER = 'LOG_OUT_USER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_ERROR'
export const REGISTER_BEGIN = 'REGISTER_BEGIN'
//SINGLE USER ACTIONS
export const GET_SINGLE_USER_BEGIN = 'GET_SINGLE_USER_BEGIN'
export const SINGLE_USER_SUCCESS = 'SINGLE_USER_SUCCESS'
export    const  SINGLE_USER_ERROR = 'SINGLE_USER_ERROR'
//ORDER ACTIONS

export const CREATE_ORDER_BEGIN = 'CREATE_ORDER_BEGIN'
export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
export const UPDATE_SORT = 'UPDATE_SORT'
// export const
